#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "This script must be run as root."
  exit 1
fi

SCRIPTDIR=$(dirname "$(realpath "$0")")

. $SCRIPTDIR/gimme.env

if [ ! -d "$SCRIPTDIR/src" ]; then
  mkdir -pv "$SCRIPTDIR/src"
fi

if [ ! -d "$SCRIPTDIR/venv" ]; then
  python3 -m venv "$SCRIPTDIR/venv"
fi

if [ ! -e tracking ]; then
  touch tracking
fi



# cat << EOF
# ENVIRONMENT VARIABLES:
# MAKEFLAGS   = $MAKEFLAGS
# XORG_PREFIX = $XORG_PREFIX
# XORG_CONFIG = $XORG_CONFIG
#
# EOF

$SCRIPTDIR/venv/bin/python3 $SCRIPTDIR/main.py "$@"
