#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "This script must be run as root."
  exit 1
fi

. ./gimme.env

# cat << EOF
# ENVIRONMENT VARIABLES:
# MAKEFLAGS   = $MAKEFLAGS
# XORG_PREFIX = $XORG_PREFIX
# XORG_CONFIG = $XORG_CONFIG
#
# EOF

python main.py "$@"
